import type { Metadata } from 'next';

// import { ColorModeProvider } from '@/contexts/ColorModeContext';
import Layout from '@/components/layout';

import 'swiper/css';
import 'swiper/css/effect-fade';
import 'swiper/css/free-mode';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/thumbs';
import { Suspense } from 'react';
import { LoadingCircle } from '@/components/common/LoadingCircle';

export const metadata: Metadata = {
  title: 'GearDN',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<LoadingCircle />}>
      <Layout>{children}</Layout>
    </Suspense>
  );
}
