import type { Metadata } from 'next';
import Layout from '@/components/layout';

import 'swiper/css';
import 'swiper/css/effect-fade';
import 'swiper/css/free-mode';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/thumbs';
import { Suspense } from 'react';
import { LoadingCircle } from '@/components/common/LoadingCircle';
import { getUserOnServer } from '@/data/profile.server';

export const metadata: Metadata = {
  title: 'GearDN | Build Your Dream Setup',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserOnServer();
  return (
    <Layout initialUser={user?.data}>
      <Suspense fallback={<LoadingCircle />}>{children}</Suspense>
    </Layout>
  );
}
