import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// import { ColorModeProvider } from '@/contexts/ColorModeContext';
import { AuthStoreProvider } from '@/providers/auth-store-provider';
import Layout from '@/components/common/sharing/layout';
import { CssBaseline } from '@mui/material';

import 'swiper/css/effect-fade';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/free-mode';
import 'swiper/css/scrollbar';
import 'swiper/css/thumbs';
import 'swiper/css';
// import { NotificationContextProvider } from '@/contexts/NotificationContext';

const inter = Inter({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'GearDN',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <CssBaseline />
      <body className={inter.className}>
        {/* <AuthStoreProvider> */}
        <Layout>{children}</Layout>
        {/* </AuthStoreProvider> */}
      </body>
    </html>
  );
}
